export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const ADD_ITEM_DUPLICATE = 'ADD_ITEM_DUPLICATE';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';

export const SET_NEW_ITEM_STATE = 'SET_NEW_ITEM_STATE';
export const SET_EDIT_ITEM_STATE = 'SET_EDIT_ITEM_STATE';




export const SET_MAP_POINT = 'SET_MAP_POINT';

export const SET_MAP_STATE = 'SET_MAP_STATE';
export const SET_EDIT_MAP_POINT = 'SET_NEW_MAP_POINT';

export const SET_NEW_MAP_POINT = 'SET_NEW_MAP_POINT';
export const SET_NEW_MAP_POINT_FINAL = 'SET_NEW_MAP_POINT_FINAL';
export const SET_NEW_MAP_ROUTE = 'SET_NEW_MAP_ROUTE';
export const SET_NEW_MAP_ROUTE_FINAL = 'SET_NEW_MAP_ROUTE_FINAL';
export const SET_NEW_MAP_ROUTE_POINT = 'SET_NEW_MAP_ROUTE_POINT';
export const SET_NEW_MAP_ROUTE_POINT_FINAL = 'SET_NEW_MAP_ROUTE_POINT_FINAL';



// Layout
export const SET_ITEM_TYPE = 'SET_ITEM_TYPE';
