// Users
export const GET_ITEMS_SUCCESS = 'GET_POINTS_SUCCESS';
export const EDIT_ITEM_SUCCESS = 'EDIT_POINT_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_POINT_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_POINT_FAILURE';
export const ADD_ITEM_DUPLICATE = 'ADD_POINT_DUPLICATE';
export const ITEM_DETAILS_SUCCESS = 'POINT_DETAILS_SUCCESS';

export const SET_NEW_ITEM_STATE = 'SET_NEW_POINT_STATE';
export const SET_EDIT_ITEM_STATE = 'SET_EDIT_POINT_STATE';

// Users
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const EDIT_ROUTE_SUCCESS = 'EDIT_ROUTE_SUCCESS';
export const ADD_ROUTE_SUCCESS = 'ADD_ROUTE_SUCCESS';
export const ADD_ROUTE_FAILURE = 'ADD_ROUTE_FAILURE';
export const ADD_ROUTE_DUPLICATE = 'ADD_ROUTE_DUPLICATE';
export const ROUTE_DETAILS_SUCCESS = 'ROUTE_DETAILS_SUCCESS';

export const SET_NEW_ROUTE_STATE = 'SET_NEW_ROUTE_STATE';
export const SET_EDIT_ROUTE_STATE = 'SET_EDIT_ROUTE_STATE';


// Layout
export const SET_ITEM_TYPE = 'SET_ITEM_TYPE';
