// Users
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const ADD_ITEM_DUPLICATE = 'ADD_ITEM_DUPLICATE';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';

export const SET_NEW_ITEM_STATE = 'SET_NEW_ITEM_STATE';
export const SET_EDIT_ITEM_STATE = 'SET_EDIT_ITEM_STATE';

