// Users
export const GET_ITEMS_SUCCESS = 'GET_ROUTES_SUCCESS';
export const EDIT_ITEM_SUCCESS = 'EDIT_ROUTES_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_ROUTES_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ROUTES_FAILURE';
export const ADD_ITEM_DUPLICATE = 'ADD_ROUTES_DUPLICATE';
export const ITEM_DETAILS_SUCCESS = 'ROUTES_DETAILS_SUCCESS';

export const SET_NEW_ITEM_STATE = 'SET_NEW_ROUTES_STATE';
export const SET_EDIT_ITEM_STATE = 'SET_EDIT_ROUTES_STATE';

